language: java

dist: trusty
sudo: required

before_install:
  - wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=pcp | sudo apt-key add -
  - echo "deb https://dl.bintray.com/pcp/trusty trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install -y pcp

script: mvn -B -V clean install verify